//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ImageProcess.rc
//
#define IDCANCEL_HISTOGRAM              2
#define FFTCANCEL                       2
#define IDMORPHOLOGYCANCEL              2
#define IDM_ABOUTBOX                    0x0010
#define IDD_DIALOG_TOOL_IMAGEPROCESS_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDR_MAINFRAME                   128
#define IDR_POPUP_MENU                  129
#define IDD_DIALOG_TOOL_IMAGEPROCESS_MFCBMP_DIALOG                                  101030101
#define IDD_DIALOG_TOOL_IMAGEPROCESS_SMOOTH_DLG                                     101030102
#define IDD_DIALOG_TOOL_IMAGEPROCESS_MEDIAN_DLG                                     101030103
#define IDD_DIALOG_TOOL_IMAGEPROCESS_FILTER_DEFINE_DLG                              101030104
#define IDD_DIALOG_TOOL_IMAGEPROCESS_CURVE_DLG                                      101030105
#define IDD_DIALOG_TOOL_IMAGEPROCESS_THRESHOLD_DLG                                  101030106
#define IDD_DIALOG_TOOL_IMAGEPROCESS_HISTOGRAM_DLG                                  101030107
#define IDD_DIALOG_TOOL_IMAGEPROCESS_ZOOM_DLG                                       101030108
#define IDD_DIALOG_TOOL_IMAGEPROCESS_FFT_DLG                                        101030109
#define IDD_DIALOG_TOOL_IMAGEPROCESS_MORPHOLOGY_DLG                                 101030110
#define IDD_DIALOG_TOOL_IMAGEPROCESS_MASK_DLG                                       101030111
#define IDD_DIALOG_TOOL_IMAGEPROCESS_THRESHOLD_EX_DLG                               101030112
#define IDD_DIALOG_TOOL_IMAGEPROCESS_GAUSS_DLG                                      101030113
#define IDD_DIALOG_TOOL_IMAGEPROCESS_BILATERAL_DLG                                  101030114

#define IDC_TOOL_IMAGEPROCESS_AIR_CURSOR_CUT                                        901030101
#define IDC_TOOL_IMAGEPROCESS_AIR_CURSOR                                            901030102
#define IDC_TOOL_IMAGEPROCESS_FILE_NAME                                             901030103
#define IDC_TOOL_IMAGEPROCESS_BUTTON2                                               901030104
#define IDC_TOOL_IMAGEPROCESS_FILE_OPEN                                             901030105
#define IDC_TOOL_IMAGEPROCESS_SAVE_FILE                                             901030106
#define IDC_TOOL_IMAGEPROCESS_SAVE_TEXT                                             901030107
#define IDC_TOOL_IMAGEPROCESS_REVERSE_COLOR                                         901030108
#define IDC_TOOL_IMAGEPROCESS_FILE_INFO                                             901030109
#define IDC_TOOL_IMAGEPROCESS_CANCEL                                                901030110
#define IDC_TOOL_IMAGEPROCESS_CANCEL_CURVE                                          901030111
#define IDC_TOOL_IMAGEPROCESS_SLIDER_X                                              901030112
#define IDC_TOOL_IMAGEPROCESS_SLIDER_Y                                              901030113
#define IDC_TOOL_IMAGEPROCESS_EDIT_X                                                901030114
#define IDC_TOOL_IMAGEPROCESS_EDIT_Y                                                901030115
#define IDC_TOOL_IMAGEPROCESS_CHECK_PREVIEW                                         901030116
#define IDC_TOOL_IMAGEPROCESS_EDIT_MEDIAN_X                                         901030117
#define IDC_TOOL_IMAGEPROCESS_EDIT_MEDIAN_Y                                         901030118
#define IDC_TOOL_IMAGEPROCESS_EDIT_00                                               901030119
#define IDC_TOOL_IMAGEPROCESS_EDIT_01                                               901030120
#define IDC_TOOL_IMAGEPROCESS_EDIT_02                                               901030121
#define IDC_TOOL_IMAGEPROCESS_EDIT_03                                               901030122
#define IDC_TOOL_IMAGEPROCESS_EDIT_04                                               901030123
#define IDC_TOOL_IMAGEPROCESS_EDIT_10                                               901030124
#define IDC_TOOL_IMAGEPROCESS_EDIT_11                                               901030125
#define IDC_TOOL_IMAGEPROCESS_EDIT_12                                               901030126
#define IDC_TOOL_IMAGEPROCESS_EDIT_13                                               901030127
#define IDC_TOOL_IMAGEPROCESS_EDIT_14                                               901030128
#define IDC_TOOL_IMAGEPROCESS_EDIT_20                                               901030129
#define IDC_TOOL_IMAGEPROCESS_EDIT_21                                               901030130
#define IDC_TOOL_IMAGEPROCESS_EDIT_22                                               901030131
#define IDC_TOOL_IMAGEPROCESS_EDIT_23                                               901030132
#define IDC_TOOL_IMAGEPROCESS_EDIT_24                                               901030133
#define IDC_TOOL_IMAGEPROCESS_EDIT_30                                               901030134
#define IDC_TOOL_IMAGEPROCESS_EDIT_31                                               901030135
#define IDC_TOOL_IMAGEPROCESS_EDIT_32                                               901030136
#define IDC_TOOL_IMAGEPROCESS_EDIT_33                                               901030137
#define IDC_TOOL_IMAGEPROCESS_EDIT_34                                               901030138
#define IDC_TOOL_IMAGEPROCESS_EDIT_40                                               901030139
#define IDC_TOOL_IMAGEPROCESS_EDIT_41                                               901030140
#define IDC_TOOL_IMAGEPROCESS_EDIT_42                                               901030141
#define IDC_TOOL_IMAGEPROCESS_EDIT_43                                               901030142
#define IDC_TOOL_IMAGEPROCESS_EDIT_44                                               901030143
#define IDC_TOOL_IMAGEPROCESS_EDIT_DIVIDE                                           901030144
#define IDC_TOOL_IMAGEPROCESS_EDIT_MOVE                                             901030145
#define IDC_TOOL_IMAGEPROCESS_COMBO_DEFAULT                                         901030146
#define IDC_TOOL_IMAGEPROCESS_COLOR_SELECT                                          901030147
#define IDC_TOOL_IMAGEPROCESS_MOUSE_X                                               901030148
#define IDC_TOOL_IMAGEPROCESS_MOUSE_Y                                               901030149
#define IDC_TOOL_IMAGEPROCESS_BTN_ADD_POINT                                         901030150
#define IDC_TOOL_IMAGEPROCESS_BTN_RELOAD                                            901030151
#define IDC_TOOL_IMAGEPROCESS_CANCEL_THRESHOLD                                      901030152
#define IDC_TOOL_IMAGEPROCESS_EDIT_THRESHOLD                                        901030153
#define IDC_TOOL_IMAGEPROCESS_BTN_CLEAR                                             901030154
#define IDC_TOOL_IMAGEPROCESS_MIN                                                   901030155
#define IDC_TOOL_IMAGEPROCESS_MAX                                                   901030156
#define IDC_TOOL_IMAGEPROCESS_PREVIEW                                               901030157
#define IDC_TOOL_IMAGEPROCESS_ORG_H                                                 901030158
#define IDC_TOOL_IMAGEPROCESS_ORG_W                                                 901030159
#define IDC_TOOL_IMAGEPROCESS_DES_H                                                 901030160
#define IDC_TOOL_IMAGEPROCESS_DES_W                                                 901030161
#define IDC_TOOL_IMAGEPROCESS_METHOD                                                901030162
#define IDC_TOOL_IMAGEPROCESS_SCALE                                                 901030163
#define IDC_TOOL_IMAGEPROCESS_AMPLITUDE                                             901030164
#define IDC_TOOL_IMAGEPROCESS_ANGLE                                                 901030165
#define IDC_TOOL_IMAGEPROCESS_FILTER                                                901030166
#define IDC_TOOL_IMAGEPROCESS_PARAM1                                                901030167
#define IDC_TOOL_IMAGEPROCESS_PARAM2                                                901030168
#define IDC_TOOL_IMAGEPROCESS_FILTER_TYPE                                           901030169
#define IDC_TOOL_IMAGEPROCESS_BTN_CONNECT_ME                                        901030170
#define IDC_TOOL_IMAGEPROCESS_TYPE                                                  901030171
#define IDC_TOOL_IMAGEPROCESS_THRESHOLD_SLD                                         901030172
#define IDC_TOOL_IMAGEPROCESS_THRESHOLD                                             901030173
#define IDC_TOOL_IMAGEPROCESS_XPOS                                                  901030174
#define IDC_TOOL_IMAGEPROCESS_YPOS                                                  901030175
#define IDC_TOOL_IMAGEPROCESS_B_AND_W                                               901030176
#define IDC_TOOL_IMAGEPROCESS_EDIT1                                                 901030177
#define IDC_TOOL_IMAGEPROCESS_METHOD_CMB                                            901030178
#define IDC_TOOL_IMAGEPROCESS_THRESHOLD_EDIT                                        901030179
#define IDC_TOOL_IMAGEPROCESS_EDIT_R                                                901030180
#define IDC_TOOL_IMAGEPROCESS_EDIT_SIGMA                                            901030181
#define IDC_TOOL_IMAGEPROCESS_SIGMA_G                                               901030182
#define IDC_TOOL_IMAGEPROCESS_SIGMA_S                                               901030183
#define IDC_TOOL_IMAGEPROCESS_R                                                     901030184
#define ID_TOOL_IMAGEPROCESS_SUB_MENU                                               901030185
#define ID_TOOL_IMAGEPROCESS_POPUP_FILE_OPEN                                        901030186
#define ID_TOOL_IMAGEPROCESS_POPUP_FILE_SAVE                                        901030187
#define ID_TOOL_IMAGEPROCESS_POPUP_FILE_SAVE_TEXT                                   901030188
#define ID_TOOL_IMAGEPROCESS_POPUP_FILE_INFO                                        901030189
#define ID_TOOL_IMAGEPROCESS_POPUP_REVERSE_LR                                       901030190
#define ID_TOOL_IMAGEPROCESS_POPUP_REVERSE_UD                                       901030191
#define ID_TOOL_IMAGEPROCESS_POPUP_REVERSE_VOLOR                                    901030192
#define ID_TOOL_IMAGEPROCESS_POPUP_REVERSE_COLOR                                    901030193
#define ID_TOOL_IMAGEPROCESS_POPUP_REVERSE_180                                      901030194
#define ID_TOOL_IMAGEPROCESS_POPUP_33_SMOOTH                                        901030195
#define ID_TOOL_IMAGEPROCESS_POPUP_55_SMOOTH                                        901030196
#define ID_TOOL_IMAGEPROCESS_POPUP_AVG_SMOOTH                                       901030197
#define ID_TOOL_IMAGEPROCESS_POPUP_33_MED                                           901030198
#define ID_TOOL_IMAGEPROCESS_POPUP_33_MEDIAN                                        901030199
#define ID_TOOL_IMAGEPROCESS_POPUP_55_MEDIAN                                        901030200
#define ID_TOOL_IMAGEPROCESS_POPUP_MEDIAN                                           901030201
#define ID_TOOL_IMAGEPROCESS_FILTER_DEFINE                                          901030202
#define ID_TOOL_IMAGEPROCESS_POPUP_POINT_INFO                                       901030203
#define ID_TOOL_IMAGEPROCESS_POPUP_CURVE                                            901030204
#define ID_TOOL_IMAGEPROCESS_HISTOGRAM_EQUALIZATION                                 901030205
#define ID_TOOL_IMAGEPROCESS_HISTOGRAM                                              901030206
#define ID_TOOL_IMAGEPROCESS_POPUP_RELOAD                                           901030207
#define ID_TOOL_IMAGEPROCESS_POPUP_THRESHOLD                                        901030208
#define ID_TOOL_IMAGEPROCESS_POPUP_LPLS_4                                           901030209
#define ID_TOOL_IMAGEPROCESS_POPUP_LPLS_8                                           901030210
#define ID_TOOL_IMAGEPROCESS_POPUP_SOBEL_H                                          901030211
#define ID_TOOL_IMAGEPROCESS_POPUP_SOBEL_W                                          901030212
#define ID_TOOL_IMAGEPROCESS_POPUP_PREWITT_H                                        901030213
#define ID_TOOL_IMAGEPROCESS_POPUP_PREWITT_W                                        901030214
#define ID_TOOL_IMAGEPROCESS_POPUP_RGB_2_GRAY                                       901030215
#define ID_TOOL_IMAGEPROCESS_POPUP_                                                 901030216
#define ID_TOOL_IMAGEPROCESS_POPUP_ZOOM                                             901030217
#define ID_TOOL_IMAGEPROCESS_POPUP_DFT                                              901030218
#define ID_TOOL_IMAGEPROCESS_POPUP_FFT                                              901030219
#define ID_TOOL_IMAGEPROCESS_POPUP_IFFT                                             901030220
#define ID_TOOL_IMAGEPROCESS_POPUP_IDFT                                             901030221
#define ID_TOOL_IMAGEPROCESS_FFT_FILTER                                             901030222
#define ID_TOOL_IMAGEPROCESS_POPUP_MORPHOLOGY                                       901030223
#define ID_TOOL_IMAGEPROCESS_POPUP_GETBOARD                                         901030224
#define ID_TOOL_IMAGEPROCESS_POPUP_MASK                                             901030225
#define ID_TOOL_IMAGEPROCESS_POPUP_THRESHOLD_EX                                     901030226
#define ID_TOOL_IMAGEPROCESS_POPUP_CUT                                              901030227
#define ID_TOOL_IMAGEPROCESS_POPUP_CUT_INFO                                         901030228
#define ID_TOOL_IMAGEPROCESS_POPUP_BILATERAL                                        901030229
#define ID_TOOL_IMAGEPROCESS_POPUP_GAUSS                                            901030230
#define ID_TOOL_IMAGEPROCESS_POPUP_GRADIENT                                         901030231


#define IDC_TOOL_IMAGEPROCESS_URL_ABOUTBOX_LINK           99998
#define IDC_TOOL_IMAGEPROCESS_URL_ABOUTBOX_BLOGLINK       99999

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32885
#define _APS_NEXT_CONTROL_VALUE         1109
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
