//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ImageProcess.rc
//
#define IDCANCEL_HISTOGRAM              2
#define FFTCANCEL                       2
#define IDMORPHOLOGYCANCEL              2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MFCBMP_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDR_POPUP_MENU                  129
#define IDD_SMOOTH_DLG                  131
#define IDD_MEDIAN_DLG                  132
#define IDD_FILTER_DEFINE_DLG           133
#define IDD_CURVE_DLG                   135
#define IDD_THRESHOLD_DLG               138
#define IDD_HISTOGRAM_DLG               139
#define IDD_ZOOM_DLG                    141
#define IDD_FFT_DLG                     143
#define IDD_MORPHOLOGY_DLG              145
#define IDD_MASK_DLG                    147
#define IDC_AIR_CURSOR                  148
#define IDD_THRESHOLD_EX_DLG            149
#define IDC_AIR_CURSOR_CUT              153
#define IDD_GAUSS_DLG                   154
#define IDD_BILATERAL_DLG               155
#define IDC_FILE_NAME                   1001
#define IDC_BUTTON2                     1002
#define IDC_FILE_OPEN                   1002
#define IDC_SAVE_FILE                   1003
#define IDC_SAVE_TEXT                   1004
#define IDC_REVERSE_COLOR               1005
#define IDC_FILE_INFO                   1005
#define BTN_IDCANCEL                    1009
#define IDCANCEL_CURVE                  1009
#define IDC_SLIDER_X                    1010
#define IDC_SLIDER_Y                    1011
#define IDC_EDIT_X                      1012
#define IDC_EDIT_Y                      1013
#define IDC_CHECK_PREVIEW               1015
#define IDC_EDIT_MEDIAN_X               1016
#define IDC_EDIT_MEDIAN_Y               1017
#define IDC_EDIT_00                     1019
#define IDC_EDIT_01                     1020
#define IDC_EDIT_02                     1021
#define IDC_EDIT_03                     1022
#define IDC_EDIT_04                     1023
#define IDC_EDIT_10                     1024
#define IDC_EDIT_11                     1025
#define IDC_EDIT_12                     1026
#define IDC_EDIT_13                     1027
#define IDC_EDIT_14                     1028
#define IDC_EDIT_20                     1029
#define IDC_EDIT_21                     1030
#define IDC_EDIT_22                     1031
#define IDC_EDIT_23                     1032
#define IDC_EDIT_24                     1033
#define IDC_EDIT_30                     1034
#define IDC_EDIT_31                     1035
#define IDC_EDIT_32                     1036
#define IDC_EDIT_33                     1037
#define IDC_EDIT_34                     1038
#define IDC_EDIT_40                     1039
#define IDC_EDIT_41                     1040
#define IDC_EDIT_42                     1041
#define IDC_EDIT_43                     1042
#define IDC_EDIT_44                     1043
#define IDC_EDIT_DIVIDE                 1044
#define IDC_EDIT_MOVE                   1045
#define IDC_COMBO_DEFAULT               1048
#define IDC_COLOR_SELECT                1050
#define IDC_MOUSE_X                     1051
#define IDC_MOUSE_Y                     1052
#define IDC_BTN_ADD_POINT               1056
#define IDC_BTN_RELOAD                  1057
#define IDCANCEL_THRESHOLD              1066
#define IDC_EDIT_THRESHOLD              1067
#define IDC_BTN_CLEAR                   1068
#define IDC_MIN                         1073
#define IDC_MAX                         1074
#define IDC_PREVIEW                     1075
#define IDC_ORG_H                       1076
#define IDC_ORG_W                       1077
#define IDC_DES_H                       1078
#define IDC_DES_W                       1079
#define IDC_METHOD                      1080
#define IDC_SCALE                       1082
#define IDC_AMPLITUDE                   1083
#define IDC_ANGLE                       1084
#define IDC_FILTER                      1085
#define IDC_PARAM1                      1086
#define IDC_PARAM2                      1087
#define IDC_FILTER_TYPE                 1089
#define IDC_BTN_CONNECT_ME              1090
#define IDC_TYPE                        1091
#define IDC_THRESHOLD_SLD               1092
#define IDC_THRESHOLD                   1093
#define IDC_XPOS                        1094
#define IDC_YPOS                        1095
#define IDC_B_AND_W                     1097
#define IDC_EDIT1                       1098
#define IDC_METHOD_CMB                  1102
#define IDC_THRESHOLD_EDIT              1103
#define IDC_EDIT_R                      1104
#define IDC_EDIT_SIGMA                  1105
#define IDC_SIGMA_G                     1106
#define IDC_SIGMA_S                     1107
#define IDC_R                           1108
#define ID_SUB_MENU                     32777
#define ID_POPUP_FILE_OPEN              32787
#define ID_POPUP_FILE_SAVE              32788
#define ID_POPUP_FILE_SAVE_TEXT         32789
#define ID_POPUP_FILE_INFO              32790
#define ID_POPUP_REVERSE_LR             32791
#define ID_POPUP_REVERSE_UD             32792
#define ID_POPUP_REVERSE_VOLOR          32793
#define ID_POPUP_REVERSE_COLOR          32794
#define ID_POPUP_REVERSE_180            32796
#define ID_POPUP_33_SMOOTH              32803
#define ID_POPUP_55_SMOOTH              32804
#define ID_POPUP_AVG_SMOOTH             32805
#define ID_POPUP_33_MED                 32809
#define ID_POPUP_33_MEDIAN              32810
#define ID_POPUP_55_MEDIAN              32811
#define ID_POPUP_MEDIAN                 32813
#define ID_FILTER_DEFINE                32816
#define ID_POPUP_POINT_INFO             32818
#define ID_POPUP_CURVE                  32820
#define ID_HISTOGRAM_EQUALIZATION       32824
#define ID_HISTOGRAM                    32825
#define ID_POPUP__RELOAD                32829
#define ID_POPUP_RELOAD                 32830
#define ID_POPUP_THRESHOLD              32832
#define ID_POPUP_LPLS_4                 32841
#define ID_POPUP_LPLS_8                 32842
#define ID_POPUP_SOBEL_H                32843
#define ID_POPUP_SOBEL_W                32844
#define ID_POPUP_PREWITT_H              32845
#define ID_POPUP_PREWITT_W              32846
#define ID_POPUP_RGB_2_GRAY             32847
#define ID_POPUP_                       32849
#define ID_POPUP_ZOOM                   32850
#define ID_POPUP_DFT                    32853
#define ID_POPUP_FFT                    32857
#define ID_POPUP_IFFT                   32858
#define ID_POPUP_IDFT                   32860
#define ID_FFT_FILTER                   32862
#define ID_POPUP_MORPHOLOGY             32864
#define ID_POPUP_GETBOARD               32867
#define ID_POPUP_MASK                   32870
#define ID_POPUP_THRESHOLD_EX           32873
#define ID_POPUP_CUT                    32875
#define ID_POPUP_CUT_INFO               32878
#define ID_POPUP_BILATERAL              32880
#define ID_POPUP_GAUSS                  32882
#define ID_POPUP_GRADIENT               32884
#define IDC_URL_ABOUTBOX_LINK           99998
#define IDC_URL_ABOUTBOX_BLOGLINK       99999

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32885
#define _APS_NEXT_CONTROL_VALUE         1109
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
